### ISSUE TITLE
大屏图表设置宽高后画布中预览错误

### ISSUE THREAD

**Issue by siyiDev** [mfish-qf/mfish-nocode-view#237]
![微信图片_20241230173144](https://github.com/user-attachments/assets/4c546b9f-0075-4129-8b67-dcd2536f74c0)
复现方式：先拖入一个图标，右侧配置栏中修改宽高，修改后画布中预览不变，图标蓝色标定框变化正确

**Comment by mfish-qf** [comment]
大屏功能还没开发完成，这几个组件是假的。。只有标签、动态标签和装饰可用

**Comment by mfish-qf** [comment]
新发布的图表已经解决这个问题，而且可以绑定动态数据了
